version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quizmaster-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456hehe
      POSTGRES_DB: quizdb
    ports:
      - '5434:5432'
    volumes:
      - quizmaster_pgdata:/var/lib/postgresql/data

volumes:
  quizmaster_pgdata:
